spring:
  data:
    mongodb:
      username: chatbotuda
      password: 4d9FusJtvErUbw68**
      host: localhost
      port: 27017
      database: chat_app
      authentication-database: admin

  server:
    port: 8088